environments:
  ephemeral:
    active_namespaces:
    - commit: df06cbad43a2
      created: '2026-01-13T23:52:01.163155'
      expires: '2026-01-14T01:52:01.856000'
      mr_id: '1491'
      name: ephemeral-fep0lt
      tests_passed: false
    - commit: df06cbad43a2
      created: '2026-01-14T12:00:40.594970'
      expires: '2026-01-14T14:00:40.608901'
      mr_id: '1491'
      name: ephemeral-mo6eze
      tests_passed: false
    - commit: df06cbad43a2
      created: '2026-01-17T00:12:46.908400'
      expires: '2026-01-17T02:12:46.923914'
      mr_id: '1491'
      name: ephemeral-x7fldo
      tests_passed: false
    cluster: ephemeral
    kubeconfig: ~/.kube/config.e
    last_check: '2026-01-17T00:12:46.908400'
    notes: ''
    status: active
  konflux:
    active_pipelines: []
    cluster: konflux
    kubeconfig: ~/.kube/config.k
    last_check: null
    namespace: aap-aa-tenant
    notes: ''
    status: unknown
  production:
    alerts: []
    cluster: crcp01ue1
    deployments: []
    known_issues: []
    kubeconfig: ~/.kube/config.p
    last_check: '2026-01-20T11:55:25.000Z'
    namespace: tower-analytics-prod
    notes: ''
    status: degraded
  stage:
    alerts: []
    cluster: crcs02ue1
    deployments: []
    known_issues: []
    kubeconfig: ~/.kube/config.s
    last_check: '2026-01-20T11:55:25.000Z'
    namespace: tower-analytics-stage
    notes: ''
    status: degraded
known_issues: []
last_checked: null
last_updated: '2026-01-19T08:59:40.382700'
recent_deployments: []
stage.alerts:
- alert: AutomationAnalyticsProcessorStoppedProcessing
  fired_at: '2026-01-18T23:30:45Z'
  status: investigating
  namespace: tower-analytics-stage
  note: processor stopped processing payloads for 24hrs - likely kafka consumer or
    db issue
