health_checks:
  gitlab_token:
    details: "GitLab check failed:           \n   ERROR  \n          \n  Get \"https://gitlab.com/api/v4/user\"\
      : dial tcp 172.65.251.78:443:"
    healthy: false
    last_checked: '2026-01-13T11:32:04.068622'
  kubeconfigs:
    details:
      ephemeral:
        expires: null
        reason: unauthorized
        valid: false
      konflux:
        expires: null
        reason: unauthorized
        valid: false
      prod:
        expires: null
        reason: unauthorized
        valid: false
      stage:
        expires: null
        reason: unauthorized
        valid: false
    healthy: false
    last_checked: '2026-01-13T11:31:49.011827'
  quay_auth:
    details: 'Quay check failed: Command timed out after 10s'
    healthy: false
    last_checked: '2026-01-13T11:31:59.024444'
  vpn:
    details: VPN disconnected (cannot reach internal clusters)
    healthy: false
    last_checked: '2026-01-13T11:31:28.980884'
last_checks:
  kubeconfig_stage_expires: '2026-01-12T23:49:06.892272'
  vpn_last_checked: '2026-01-13T11:32:04.070023'
  vpn_status: disconnected
